// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct AVFrameSideData {
 *     enum AVFrameSideDataType type;
 *     uint8_t* data;
 *     size_t size;
 *     AVDictionary* metadata;
 *     AVBufferRef* buf;
 * };
 * }
 */
public class AVFrameSideData {

    public static MemoryLayout $LAYOUT() {
        return constants$162.const$4;
    }
    public static VarHandle type$VH() {
        return constants$162.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enum AVFrameSideDataType type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)constants$162.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enum AVFrameSideDataType type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        constants$162.const$5.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)constants$162.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        constants$162.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle data$VH() {
        return constants$163.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t* data;
     * }
     */
    public static MemorySegment data$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$163.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t* data;
     * }
     */
    public static void data$set(MemorySegment seg, MemorySegment x) {
        constants$163.const$0.set(seg, x);
    }
    public static MemorySegment data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$163.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void data$set(MemorySegment seg, long index, MemorySegment x) {
        constants$163.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle size$VH() {
        return constants$163.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t size;
     * }
     */
    public static long size$get(MemorySegment seg) {
        return (long)constants$163.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t size;
     * }
     */
    public static void size$set(MemorySegment seg, long x) {
        constants$163.const$1.set(seg, x);
    }
    public static long size$get(MemorySegment seg, long index) {
        return (long)constants$163.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void size$set(MemorySegment seg, long index, long x) {
        constants$163.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle metadata$VH() {
        return constants$163.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * AVDictionary* metadata;
     * }
     */
    public static MemorySegment metadata$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$163.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * AVDictionary* metadata;
     * }
     */
    public static void metadata$set(MemorySegment seg, MemorySegment x) {
        constants$163.const$2.set(seg, x);
    }
    public static MemorySegment metadata$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$163.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void metadata$set(MemorySegment seg, long index, MemorySegment x) {
        constants$163.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle buf$VH() {
        return constants$163.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * AVBufferRef* buf;
     * }
     */
    public static MemorySegment buf$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$163.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * AVBufferRef* buf;
     * }
     */
    public static void buf$set(MemorySegment seg, MemorySegment x) {
        constants$163.const$3.set(seg, x);
    }
    public static MemorySegment buf$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$163.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void buf$set(MemorySegment seg, long index, MemorySegment x) {
        constants$163.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


