// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$147 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$147() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_vlog",
        constants$147.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_log_get_level",
        constants$3.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_log_set_level",
        constants$99.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(av_log_set_callback$callback.class, "apply", constants$147.const$0);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$147.const$0
    );
}


