// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$245 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$245() {}
    static final VarHandle const$0 = constants$244.const$5.varHandle(MemoryLayout.PathElement.groupElement("format"));
    static final VarHandle const$1 = constants$244.const$5.varHandle(MemoryLayout.PathElement.groupElement("start_display_time"));
    static final VarHandle const$2 = constants$244.const$5.varHandle(MemoryLayout.PathElement.groupElement("end_display_time"));
    static final VarHandle const$3 = constants$244.const$5.varHandle(MemoryLayout.PathElement.groupElement("num_rects"));
    static final VarHandle const$4 = constants$244.const$5.varHandle(MemoryLayout.PathElement.groupElement("rects"));
    static final VarHandle const$5 = constants$244.const$5.varHandle(MemoryLayout.PathElement.groupElement("pts"));
}


