// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$64 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$64() {}
    static final VarHandle const$0 = constants$60.const$4.varHandle(MemoryLayout.PathElement.groupElement("_lock"));
    static final VarHandle const$1 = constants$60.const$4.varHandle(MemoryLayout.PathElement.groupElement("_offset"));
    static final VarHandle const$2 = constants$60.const$4.varHandle(MemoryLayout.PathElement.groupElement("_codecvt"));
    static final VarHandle const$3 = constants$60.const$4.varHandle(MemoryLayout.PathElement.groupElement("_wide_data"));
    static final VarHandle const$4 = constants$60.const$4.varHandle(MemoryLayout.PathElement.groupElement("_freeres_list"));
    static final VarHandle const$5 = constants$60.const$4.varHandle(MemoryLayout.PathElement.groupElement("_freeres_buf"));
}


