// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$161 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$161() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_channel_layout_copy",
        constants$66.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_channel_layout_describe",
        constants$114.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_channel_layout_describe_bprint",
        constants$66.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_channel_layout_channel_from_index",
        constants$82.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_channel_layout_index_from_channel",
        constants$82.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_channel_layout_index_from_string",
        constants$66.const$1
    );
}


