// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$107 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$107() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "aligned_alloc",
        constants$105.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid();
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "abort",
        constants$107.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(atexit$__func.class, "apply", constants$107.const$1);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$107.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "atexit",
        constants$0.const$3
    );
}


