// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$339 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$339() {}
    static final VarHandle const$0 = constants$338.const$0.varHandle(MemoryLayout.PathElement.groupElement("alias"));
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_get_bits_per_pixel",
        constants$0.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_get_padded_bits_per_pixel",
        constants$0.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_pix_fmt_desc_get",
        constants$0.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_pix_fmt_desc_next",
        constants$69.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_pix_fmt_desc_get_id",
        constants$0.const$3
    );
}


