// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$291 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$291() {}
    static final VarHandle const$0 = constants$290.const$1.varHandle(MemoryLayout.PathElement.groupElement("audio_codec"));
    static final VarHandle const$1 = constants$290.const$1.varHandle(MemoryLayout.PathElement.groupElement("video_codec"));
    static final VarHandle const$2 = constants$290.const$1.varHandle(MemoryLayout.PathElement.groupElement("subtitle_codec"));
    static final VarHandle const$3 = constants$290.const$1.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    static final VarHandle const$4 = constants$290.const$1.varHandle(MemoryLayout.PathElement.groupElement("codec_tag"));
    static final VarHandle const$5 = constants$290.const$1.varHandle(MemoryLayout.PathElement.groupElement("priv_class"));
}


