// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$124 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$124() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "strcspn",
        constants$124.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "strspn",
        constants$124.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "strpbrk",
        constants$69.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "strstr",
        constants$69.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "strtok",
        constants$69.const$5
    );
}


