// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$74 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$74() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fgetc",
        constants$0.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getc",
        constants$0.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getchar",
        constants$3.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getc_unlocked",
        constants$0.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getchar_unlocked",
        constants$3.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fgetc_unlocked",
        constants$0.const$3
    );
}


