// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$194 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$194() {}
    static final VarHandle const$0 = constants$193.const$1.varHandle(MemoryLayout.PathElement.groupElement("props"));
    static final VarHandle const$1 = constants$193.const$1.varHandle(MemoryLayout.PathElement.groupElement("mime_types"));
    static final VarHandle const$2 = constants$193.const$1.varHandle(MemoryLayout.PathElement.groupElement("profiles"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "avcodec_descriptor_get",
        constants$0.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "avcodec_descriptor_next",
        constants$69.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "avcodec_descriptor_get_by_name",
        constants$69.const$2
    );
}


