// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$260 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$260() {}
    static final VarHandle const$0 = constants$258.const$5.varHandle(MemoryLayout.PathElement.groupElement("tm_wday"));
    static final VarHandle const$1 = constants$258.const$5.varHandle(MemoryLayout.PathElement.groupElement("tm_yday"));
    static final VarHandle const$2 = constants$258.const$5.varHandle(MemoryLayout.PathElement.groupElement("tm_isdst"));
    static final VarHandle const$3 = constants$258.const$5.varHandle(MemoryLayout.PathElement.groupElement("tm_gmtoff"));
    static final VarHandle const$4 = constants$258.const$5.varHandle(MemoryLayout.PathElement.groupElement("tm_zone"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("it_interval"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("it_value")
    ).withName("itimerspec");
}


