// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$151 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$151() {}
    static final VarHandle const$0 = constants$150.const$3.varHandle(MemoryLayout.PathElement.groupElement("size"));
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_buffer_alloc",
        constants$89.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_buffer_allocz",
        constants$89.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(av_buffer_create$free.class, "apply", constants$71.const$5);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$71.const$5
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "av_buffer_create",
        constants$151.const$5
    );
}


