// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$300 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$300() {}
    static final VarHandle const$0 = constants$299.const$1.varHandle(MemoryLayout.PathElement.groupElement("priv_data"));
    static final VarHandle const$1 = constants$299.const$1.varHandle(MemoryLayout.PathElement.groupElement("start_time"));
    static final VarHandle const$2 = constants$299.const$1.varHandle(MemoryLayout.PathElement.groupElement("duration"));
    static final VarHandle const$3 = constants$299.const$1.varHandle(MemoryLayout.PathElement.groupElement("nb_frames"));
    static final VarHandle const$4 = constants$299.const$1.varHandle(MemoryLayout.PathElement.groupElement("disposition"));
    static final VarHandle const$5 = constants$299.const$1.varHandle(MemoryLayout.PathElement.groupElement("discard"));
}


