// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$131 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$131() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_dynarray_add_nofree",
        constants$71.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_dynarray2_add",
        constants$131.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_size_mult",
        constants$131.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_max_alloc",
        constants$101.const$2
    );
}


