// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$258 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$258() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "avcodec_flush_buffers",
        constants$70.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_get_audio_frame_duration",
        constants$82.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_fast_padded_malloc",
        constants$70.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_fast_padded_mallocz",
        constants$70.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "avcodec_is_open",
        constants$0.const$3
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("tm_sec"),
        JAVA_INT.withName("tm_min"),
        JAVA_INT.withName("tm_hour"),
        JAVA_INT.withName("tm_mday"),
        JAVA_INT.withName("tm_mon"),
        JAVA_INT.withName("tm_year"),
        JAVA_INT.withName("tm_wday"),
        JAVA_INT.withName("tm_yday"),
        JAVA_INT.withName("tm_isdst"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("tm_gmtoff"),
        RuntimeHelper.POINTER.withName("tm_zone")
    ).withName("tm");
}


