// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$240 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$240() {}
    static final VarHandle const$0 = constants$238.const$5.varHandle(MemoryLayout.PathElement.groupElement("alloc_frame"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(AVHWAccel.start_frame.class, "apply", constants$66.const$0);
    static final VarHandle const$2 = constants$238.const$5.varHandle(MemoryLayout.PathElement.groupElement("start_frame"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(AVHWAccel.decode_params.class, "apply", constants$183.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$183.const$2
    );
    static final VarHandle const$5 = constants$238.const$5.varHandle(MemoryLayout.PathElement.groupElement("decode_params"));
}


