// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$351 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$351() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sws_allocVec",
        constants$0.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_DOUBLE,
        JAVA_DOUBLE
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sws_getGaussianVec",
        constants$351.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_DOUBLE
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "sws_scaleVec",
        constants$351.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "sws_normalizeVec",
        constants$351.const$3
    );
}


