// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$182 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$182() {}
    static final VarHandle const$0 = constants$181.const$4.varHandle(MemoryLayout.PathElement.groupElement("valid_sw_formats"));
    static final VarHandle const$1 = constants$181.const$4.varHandle(MemoryLayout.PathElement.groupElement("min_width"));
    static final VarHandle const$2 = constants$181.const$4.varHandle(MemoryLayout.PathElement.groupElement("min_height"));
    static final VarHandle const$3 = constants$181.const$4.varHandle(MemoryLayout.PathElement.groupElement("max_width"));
    static final VarHandle const$4 = constants$181.const$4.varHandle(MemoryLayout.PathElement.groupElement("max_height"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_hwdevice_hwconfig_alloc",
        constants$67.const$1
    );
}


