// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$346 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$346() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "swscale_configuration",
        constants$4.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "swscale_license",
        constants$4.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sws_getCoefficients",
        constants$0.const$1
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("coeff"),
        JAVA_INT.withName("length"),
        MemoryLayout.paddingLayout(4)
    ).withName("SwsVector");
    static final VarHandle const$4 = constants$346.const$3.varHandle(MemoryLayout.PathElement.groupElement("coeff"));
    static final VarHandle const$5 = constants$346.const$3.varHandle(MemoryLayout.PathElement.groupElement("length"));
}


