// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$171 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$171() {}
    static final VarHandle const$0 = constants$167.const$4.varHandle(MemoryLayout.PathElement.groupElement("channel_layout"));
    static final VarHandle const$1 = constants$167.const$4.varHandle(MemoryLayout.PathElement.groupElement("extended_buf"));
    static final VarHandle const$2 = constants$167.const$4.varHandle(MemoryLayout.PathElement.groupElement("nb_extended_buf"));
    static final VarHandle const$3 = constants$167.const$4.varHandle(MemoryLayout.PathElement.groupElement("side_data"));
    static final VarHandle const$4 = constants$167.const$4.varHandle(MemoryLayout.PathElement.groupElement("nb_side_data"));
    static final VarHandle const$5 = constants$167.const$4.varHandle(MemoryLayout.PathElement.groupElement("flags"));
}


