// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$244 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$244() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "avcodec_get_class",
        constants$4.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "avcodec_get_subtitle_rect_class",
        constants$4.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "avcodec_parameters_from_context",
        constants$66.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "avcodec_parameters_to_context",
        constants$66.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "avcodec_open2",
        constants$71.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "avcodec_close",
        constants$0.const$3
    );
}


