// Generated by jextract

package com.chrisribble.ffmpeg6;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$132 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$132() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_realloc",
        constants$108.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_reallocp",
        constants$117.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_realloc_f",
        constants$109.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_realloc_array",
        constants$109.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_reallocp_array",
        constants$109.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_fast_realloc",
        constants$119.const$0
    );
}


