// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct AVBufferRef {
 *     struct AVBuffer* buffer;
 *     unsigned char* data;
 *     unsigned long size;
 * };
 * }
 */
public class AVBufferRef {

    public static MemoryLayout $LAYOUT() {
        return constants$148.const$3;
    }
    public static VarHandle buffer$VH() {
        return constants$148.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct AVBuffer* buffer;
     * }
     */
    public static MemorySegment buffer$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$148.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct AVBuffer* buffer;
     * }
     */
    public static void buffer$set(MemorySegment seg, MemorySegment x) {
        constants$148.const$4.set(seg, x);
    }
    public static MemorySegment buffer$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$148.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void buffer$set(MemorySegment seg, long index, MemorySegment x) {
        constants$148.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle data$VH() {
        return constants$148.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned char* data;
     * }
     */
    public static MemorySegment data$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$148.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned char* data;
     * }
     */
    public static void data$set(MemorySegment seg, MemorySegment x) {
        constants$148.const$5.set(seg, x);
    }
    public static MemorySegment data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$148.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void data$set(MemorySegment seg, long index, MemorySegment x) {
        constants$148.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle size$VH() {
        return constants$149.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned long size;
     * }
     */
    public static long size$get(MemorySegment seg) {
        return (long)constants$149.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned long size;
     * }
     */
    public static void size$set(MemorySegment seg, long x) {
        constants$149.const$0.set(seg, x);
    }
    public static long size$get(MemorySegment seg, long index) {
        return (long)constants$149.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void size$set(MemorySegment seg, long index, long x) {
        constants$149.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


