// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct AVIndexEntry {
 *     int64_t pos;
 *     int64_t timestamp;
 *      *     int flags;
 *     int size;
 *     int min_distance;
 * };
 * }
 */
public class AVIndexEntry {

    public static MemoryLayout $LAYOUT() {
        return constants$307.const$1;
    }
    public static VarHandle pos$VH() {
        return constants$307.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t pos;
     * }
     */
    public static long pos$get(MemorySegment seg) {
        return (long)constants$307.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t pos;
     * }
     */
    public static void pos$set(MemorySegment seg, long x) {
        constants$307.const$2.set(seg, x);
    }
    public static long pos$get(MemorySegment seg, long index) {
        return (long)constants$307.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void pos$set(MemorySegment seg, long index, long x) {
        constants$307.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle timestamp$VH() {
        return constants$307.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t timestamp;
     * }
     */
    public static long timestamp$get(MemorySegment seg) {
        return (long)constants$307.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t timestamp;
     * }
     */
    public static void timestamp$set(MemorySegment seg, long x) {
        constants$307.const$3.set(seg, x);
    }
    public static long timestamp$get(MemorySegment seg, long index) {
        return (long)constants$307.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void timestamp$set(MemorySegment seg, long index, long x) {
        constants$307.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle min_distance$VH() {
        return constants$307.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int min_distance;
     * }
     */
    public static int min_distance$get(MemorySegment seg) {
        return (int)constants$307.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int min_distance;
     * }
     */
    public static void min_distance$set(MemorySegment seg, int x) {
        constants$307.const$4.set(seg, x);
    }
    public static int min_distance$get(MemorySegment seg, long index) {
        return (int)constants$307.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void min_distance$set(MemorySegment seg, long index, int x) {
        constants$307.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


