// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct AVProducerReferenceTime {
 *     int64_t wallclock;
 *     int flags;
 * };
 * }
 */
public class AVProducerReferenceTime {

    public static MemoryLayout $LAYOUT() {
        return constants$203.const$0;
    }
    public static VarHandle wallclock$VH() {
        return constants$203.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t wallclock;
     * }
     */
    public static long wallclock$get(MemorySegment seg) {
        return (long)constants$203.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t wallclock;
     * }
     */
    public static void wallclock$set(MemorySegment seg, long x) {
        constants$203.const$1.set(seg, x);
    }
    public static long wallclock$get(MemorySegment seg, long index) {
        return (long)constants$203.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void wallclock$set(MemorySegment seg, long index, long x) {
        constants$203.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle flags$VH() {
        return constants$203.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int flags;
     * }
     */
    public static int flags$get(MemorySegment seg) {
        return (int)constants$203.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int flags;
     * }
     */
    public static void flags$set(MemorySegment seg, int x) {
        constants$203.const$2.set(seg, x);
    }
    public static int flags$get(MemorySegment seg, long index) {
        return (int)constants$203.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void flags$set(MemorySegment seg, long index, int x) {
        constants$203.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


