// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$252 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$252() {}
    static final VarHandle const$0 = constants$249.const$0.varHandle(MemoryLayout.PathElement.groupElement("dts_ref_dts_delta"));
    static final VarHandle const$1 = constants$249.const$0.varHandle(MemoryLayout.PathElement.groupElement("pts_dts_delta"));
    static final VarHandle const$2 = constants$249.const$0.varHandle(MemoryLayout.PathElement.groupElement("pos"));
    static final VarHandle const$3 = constants$249.const$0.varHandle(MemoryLayout.PathElement.groupElement("last_pos"));
    static final VarHandle const$4 = constants$249.const$0.varHandle(MemoryLayout.PathElement.groupElement("duration"));
    static final VarHandle const$5 = constants$249.const$0.varHandle(MemoryLayout.PathElement.groupElement("field_order"));
}


