// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$346 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$346() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_pix_fmt_count_planes",
        constants$1.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_color_range_name",
        constants$0.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_color_range_from_name",
        constants$0.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_color_primaries_name",
        constants$0.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_color_primaries_from_name",
        constants$0.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_color_transfer_name",
        constants$0.const$1
    );
}


