// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$312 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$312() {}
    static final VarHandle const$0 = constants$311.const$0.varHandle(MemoryLayout.PathElement.groupElement("metadata"));
    static final VarHandle const$1 = constants$311.const$0.varHandle(MemoryLayout.PathElement.groupElement("program_num"));
    static final VarHandle const$2 = constants$311.const$0.varHandle(MemoryLayout.PathElement.groupElement("pmt_pid"));
    static final VarHandle const$3 = constants$311.const$0.varHandle(MemoryLayout.PathElement.groupElement("pcr_pid"));
    static final VarHandle const$4 = constants$311.const$0.varHandle(MemoryLayout.PathElement.groupElement("pmt_version"));
    static final VarHandle const$5 = constants$311.const$0.varHandle(MemoryLayout.PathElement.groupElement("start_time"));
}


