// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$75 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$75() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fputc",
        constants$72.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "putc",
        constants$72.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "putchar",
        constants$1.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fputc_unlocked",
        constants$72.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "putc_unlocked",
        constants$72.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "putchar_unlocked",
        constants$1.const$0
    );
}


