// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$147 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$147() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_log_format_line2",
        constants$147.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_log_set_flags",
        constants$98.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_log_get_flags",
        constants$3.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_int_list_length_for_size",
        constants$124.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_fopen_utf8",
        constants$67.const$4
    );
}


