// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$358 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$358() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sws_convertPalette8ToPacked32",
        constants$333.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "sws_convertPalette8ToPacked24",
        constants$333.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sws_get_class",
        constants$4.const$0
    );
    static final MemorySegment const$3 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("l");
    static final MemorySegment const$4 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("d");
    static final MemorySegment const$5 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ld");
}


