// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$356 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$356() {}
    static final VarHandle const$0 = constants$355.const$4.varHandle(MemoryLayout.PathElement.groupElement("lumV"));
    static final VarHandle const$1 = constants$355.const$4.varHandle(MemoryLayout.PathElement.groupElement("chrH"));
    static final VarHandle const$2 = constants$355.const$4.varHandle(MemoryLayout.PathElement.groupElement("chrV"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sws_isSupportedInput",
        constants$1.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "sws_isSupportedOutput",
        constants$1.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "sws_isSupportedEndiannessConversion",
        constants$1.const$0
    );
}


