// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$166 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$166() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_channel_layout_check",
        constants$0.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_channel_layout_compare",
        constants$68.const$3
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("data"),
        JAVA_LONG.withName("size"),
        RuntimeHelper.POINTER.withName("metadata"),
        RuntimeHelper.POINTER.withName("buf")
    ).withName("AVFrameSideData");
    static final VarHandle const$3 = constants$166.const$2.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$4 = constants$166.const$2.varHandle(MemoryLayout.PathElement.groupElement("data"));
    static final VarHandle const$5 = constants$166.const$2.varHandle(MemoryLayout.PathElement.groupElement("size"));
}


