// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$29 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$29() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "__trunc",
        constants$8.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_DOUBLE,
        JAVA_DOUBLE,
        JAVA_DOUBLE,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "remquo",
        constants$29.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "__remquo",
        constants$29.const$1
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_DOUBLE
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "lrint",
        constants$29.const$4
    );
}


