// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$140 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$140() {}
    static final VarHandle const$0 = constants$139.const$4.varHandle(MemoryLayout.PathElement.groupElement("f"));
    static final UnionLayout const$1 = MemoryLayout.unionLayout(
        JAVA_LONG.withName("i"),
        JAVA_DOUBLE.withName("f")
    ).withName("av_intfloat64");
    static final VarHandle const$2 = constants$140.const$1.varHandle(MemoryLayout.PathElement.groupElement("i"));
    static final VarHandle const$3 = constants$140.const$1.varHandle(MemoryLayout.PathElement.groupElement("f"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_gcd",
        constants$140.const$4
    );
}


