// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$36 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$36() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "__atan2f",
        constants$35.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "cosf",
        constants$34.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "__cosf",
        constants$34.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sinf",
        constants$34.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "__sinf",
        constants$34.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "tanf",
        constants$34.const$3
    );
}


