// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "scalbn",
        constants$14.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "__scalbn",
        constants$14.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ilogb",
        constants$7.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "__ilogb",
        constants$7.const$1
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_DOUBLE,
        JAVA_DOUBLE,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "scalbln",
        constants$27.const$4
    );
}


