// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$92 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$92() {}
    static final VarHandle const$0 = constants$91.const$5.varHandle(MemoryLayout.PathElement.groupElement("__readers"));
    static final VarHandle const$1 = constants$91.const$5.varHandle(MemoryLayout.PathElement.groupElement("__writers"));
    static final VarHandle const$2 = constants$91.const$5.varHandle(MemoryLayout.PathElement.groupElement("__wrphase_futex"));
    static final VarHandle const$3 = constants$91.const$5.varHandle(MemoryLayout.PathElement.groupElement("__writers_futex"));
    static final VarHandle const$4 = constants$91.const$5.varHandle(MemoryLayout.PathElement.groupElement("__pad3"));
    static final VarHandle const$5 = constants$91.const$5.varHandle(MemoryLayout.PathElement.groupElement("__pad4"));
}


