// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$53 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$53() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "scalbnf",
        constants$40.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "__scalbnf",
        constants$40.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ilogbf",
        constants$33.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "__ilogbf",
        constants$33.const$0
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "scalblnf",
        constants$53.const$4
    );
}


