// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$187 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$187() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_hwframe_map",
        constants$66.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_hwframe_ctx_create_derived",
        constants$183.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "avcodec_get_type",
        constants$1.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "avcodec_get_name",
        constants$0.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_get_bits_per_sample",
        constants$1.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_get_exact_bits_per_sample",
        constants$1.const$0
    );
}


