// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$170 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$170() {}
    static final VarHandle const$0 = constants$168.const$2.varHandle(MemoryLayout.PathElement.groupElement("coded_picture_number"));
    static final VarHandle const$1 = constants$168.const$2.varHandle(MemoryLayout.PathElement.groupElement("display_picture_number"));
    static final VarHandle const$2 = constants$168.const$2.varHandle(MemoryLayout.PathElement.groupElement("quality"));
    static final VarHandle const$3 = constants$168.const$2.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final VarHandle const$4 = constants$168.const$2.varHandle(MemoryLayout.PathElement.groupElement("repeat_pict"));
    static final VarHandle const$5 = constants$168.const$2.varHandle(MemoryLayout.PathElement.groupElement("interlaced_frame"));
}


