// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$146 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$146() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(AVClass.child_next.class, "apply", constants$69.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$69.const$5
    );
    static final VarHandle const$2 = constants$143.const$2.varHandle(MemoryLayout.PathElement.groupElement("child_next"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(AVClass.child_class_iterate.class, "apply", constants$69.const$2);
    static final VarHandle const$4 = constants$143.const$2.varHandle(MemoryLayout.PathElement.groupElement("child_class_iterate"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandleVariadic(
        "av_log",
        constants$146.const$5
    );
}


