// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$134 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$134() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("num"),
        JAVA_INT.withName("den")
    ).withName("AVRational");
    static final VarHandle const$1 = constants$134.const$0.varHandle(MemoryLayout.PathElement.groupElement("num"));
    static final VarHandle const$2 = constants$134.const$0.varHandle(MemoryLayout.PathElement.groupElement("den"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_reduce",
        constants$134.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("num"),
        JAVA_INT.withName("den")
    ).withName("AVRational"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("num"),
            JAVA_INT.withName("den")
        ).withName("AVRational"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("num"),
            JAVA_INT.withName("den")
        ).withName("AVRational")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "av_mul_q",
        constants$134.const$5
    );
}


