// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$330 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$330() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_read_frame",
        constants$66.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_seek_frame",
        constants$301.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "avformat_seek_file",
        constants$303.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "avformat_flush",
        constants$0.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_read_play",
        constants$0.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_read_pause",
        constants$0.const$3
    );
}


