// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$158 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$158() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_dict_copy",
        constants$66.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_dict_free",
        constants$72.const$4
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_BYTE,
        JAVA_BYTE
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_dict_get_string",
        constants$158.const$2
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("id"),
        MemoryLayout.sequenceLayout(16, JAVA_BYTE).withName("name"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("AVChannelCustom");
    static final VarHandle const$5 = constants$158.const$4.varHandle(MemoryLayout.PathElement.groupElement("id"));
}


