// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$246 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$246() {}
    static final VarHandle const$0 = constants$245.const$4.varHandle(MemoryLayout.PathElement.groupElement("start_display_time"));
    static final VarHandle const$1 = constants$245.const$4.varHandle(MemoryLayout.PathElement.groupElement("end_display_time"));
    static final VarHandle const$2 = constants$245.const$4.varHandle(MemoryLayout.PathElement.groupElement("num_rects"));
    static final VarHandle const$3 = constants$245.const$4.varHandle(MemoryLayout.PathElement.groupElement("rects"));
    static final VarHandle const$4 = constants$245.const$4.varHandle(MemoryLayout.PathElement.groupElement("pts"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "avcodec_version",
        constants$3.const$4
    );
}


