// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$348 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$348() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_find_best_pix_fmt_of_2",
        constants$348.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_image_fill_max_pixsteps",
        constants$132.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_image_get_linesize",
        constants$347.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_image_fill_linesizes",
        constants$338.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_image_fill_plane_sizes",
        constants$257.const$2
    );
}


