// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$148 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$148() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("num"),
        JAVA_INT.withName("den")
    ).withName("AVRational"));
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_get_time_base_q",
        constants$148.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_fourcc_make_string",
        constants$122.const$2
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffer"),
        RuntimeHelper.POINTER.withName("data"),
        JAVA_LONG.withName("size")
    ).withName("AVBufferRef");
    static final VarHandle const$4 = constants$148.const$3.varHandle(MemoryLayout.PathElement.groupElement("buffer"));
    static final VarHandle const$5 = constants$148.const$3.varHandle(MemoryLayout.PathElement.groupElement("data"));
}


