// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$283 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$283() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "avio_wb32",
        constants$160.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "avio_wl24",
        constants$160.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "avio_wb24",
        constants$160.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "avio_wl16",
        constants$160.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "avio_wb16",
        constants$160.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "avio_put_str",
        constants$66.const$1
    );
}


