// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$150 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$150() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_buffer_realloc",
        constants$114.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_buffer_replace",
        constants$66.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(av_buffer_pool_init$alloc.class, "apply", constants$86.const$2);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$86.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_buffer_pool_init",
        constants$150.const$4
    );
}


