// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$151 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$151() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_buffer_make_writable",
        constants$0.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_buffer_realloc",
        constants$116.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_buffer_replace",
        constants$66.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(av_buffer_pool_init$alloc.class, "apply", constants$87.const$0);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$87.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "av_buffer_pool_init",
        constants$151.const$5
    );
}


