// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$323 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$323() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(AVFormatContext.io_open.class, "apply", constants$322.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$322.const$5
    );
    static final VarHandle const$2 = constants$311.const$5.varHandle(MemoryLayout.PathElement.groupElement("io_open"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(AVFormatContext.io_close.class, "apply", constants$69.const$3);
    static final VarHandle const$4 = constants$311.const$5.varHandle(MemoryLayout.PathElement.groupElement("io_close"));
    static final VarHandle const$5 = constants$311.const$5.varHandle(MemoryLayout.PathElement.groupElement("protocol_blacklist"));
}


