// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$134 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$134() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_strndup",
        constants$108.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_memdup",
        constants$108.const$3
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_memcpy_backptr",
        constants$134.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_dynarray_add",
        constants$134.const$4
    );
}


