// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$242 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$242() {}
    static final VarHandle const$0 = constants$241.const$4.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$1 = constants$241.const$4.varHandle(MemoryLayout.PathElement.groupElement("w"));
    static final VarHandle const$2 = constants$241.const$4.varHandle(MemoryLayout.PathElement.groupElement("h"));
    static final VarHandle const$3 = constants$241.const$4.varHandle(MemoryLayout.PathElement.groupElement("nb_colors"));
    static final VarHandle const$4 = constants$241.const$4.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$5 = constants$241.const$4.varHandle(MemoryLayout.PathElement.groupElement("text"));
}


