// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$299 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$299() {}
    static final VarHandle const$0 = constants$298.const$5.varHandle(MemoryLayout.PathElement.groupElement("name"));
    static final VarHandle const$1 = constants$298.const$5.varHandle(MemoryLayout.PathElement.groupElement("long_name"));
    static final VarHandle const$2 = constants$298.const$5.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    static final VarHandle const$3 = constants$298.const$5.varHandle(MemoryLayout.PathElement.groupElement("extensions"));
    static final VarHandle const$4 = constants$298.const$5.varHandle(MemoryLayout.PathElement.groupElement("codec_tag"));
    static final VarHandle const$5 = constants$298.const$5.varHandle(MemoryLayout.PathElement.groupElement("priv_class"));
}


