// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$143 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$143() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(AVClass.query_ranges.class, "apply", constants$143.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$143.const$0
    );
    static final VarHandle const$3 = constants$140.const$5.varHandle(MemoryLayout.PathElement.groupElement("query_ranges"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(AVClass.child_next.class, "apply", constants$67.const$4);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$67.const$4
    );
}


