// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$311 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$311() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("id"),
        JAVA_INT.withName("flags"),
        JAVA_INT.withName("discard"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("stream_index"),
        JAVA_INT.withName("nb_stream_indexes"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("metadata"),
        JAVA_INT.withName("program_num"),
        JAVA_INT.withName("pmt_pid"),
        JAVA_INT.withName("pcr_pid"),
        JAVA_INT.withName("pmt_version"),
        JAVA_LONG.withName("start_time"),
        JAVA_LONG.withName("end_time"),
        JAVA_LONG.withName("pts_wrap_reference"),
        JAVA_INT.withName("pts_wrap_behavior"),
        MemoryLayout.paddingLayout(4)
    ).withName("AVProgram");
    static final VarHandle const$1 = constants$311.const$0.varHandle(MemoryLayout.PathElement.groupElement("id"));
    static final VarHandle const$2 = constants$311.const$0.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    static final VarHandle const$3 = constants$311.const$0.varHandle(MemoryLayout.PathElement.groupElement("discard"));
    static final VarHandle const$4 = constants$311.const$0.varHandle(MemoryLayout.PathElement.groupElement("stream_index"));
    static final VarHandle const$5 = constants$311.const$0.varHandle(MemoryLayout.PathElement.groupElement("nb_stream_indexes"));
}


