// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$148 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$148() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(av_log_set_callback$callback.class, "apply", constants$147.const$2);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$147.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_log_set_callback",
        constants$72.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_log_default_callback",
        constants$147.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_default_item_name",
        constants$69.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_default_get_category",
        constants$0.const$3
    );
}


