// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$178 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$178() {}
    static final VarHandle const$0 = constants$176.const$4.varHandle(MemoryLayout.PathElement.groupElement("user_opaque"));
    static final VarHandle const$1 = constants$176.const$4.varHandle(MemoryLayout.PathElement.groupElement("pool"));
    static final VarHandle const$2 = constants$176.const$4.varHandle(MemoryLayout.PathElement.groupElement("initial_pool_size"));
    static final VarHandle const$3 = constants$176.const$4.varHandle(MemoryLayout.PathElement.groupElement("format"));
    static final VarHandle const$4 = constants$176.const$4.varHandle(MemoryLayout.PathElement.groupElement("sw_format"));
    static final VarHandle const$5 = constants$176.const$4.varHandle(MemoryLayout.PathElement.groupElement("width"));
}


