// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$184 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$184() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_hwdevice_get_hwframe_constraints",
        constants$67.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_hwframe_constraints_free",
        constants$70.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_hwframe_map",
        constants$110.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_hwframe_ctx_create_derived",
        constants$181.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "avcodec_get_type",
        constants$1.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "avcodec_get_name",
        constants$0.const$1
    );
}


