// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$310 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$310() {}
    static final VarHandle const$0 = constants$308.const$1.varHandle(MemoryLayout.PathElement.groupElement("nb_side_data"));
    static final VarHandle const$1 = constants$308.const$1.varHandle(MemoryLayout.PathElement.groupElement("event_flags"));
    static final VarHandle const$2 = constants$308.const$1.varHandle(MemoryLayout.PathElement.groupElement("codecpar"));
    static final VarHandle const$3 = constants$308.const$1.varHandle(MemoryLayout.PathElement.groupElement("pts_wrap_bits"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_stream_get_parser",
        constants$69.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_stream_get_end_pts",
        constants$82.const$0
    );
}


