// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$288 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$288() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "avio_get_str16le",
        constants$181.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "avio_get_str16be",
        constants$181.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "avio_open",
        constants$110.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "avio_open2",
        constants$288.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "avio_close",
        constants$0.const$3
    );
}


