// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$353 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$353() {}
    static final VarHandle const$0 = constants$352.const$2.varHandle(MemoryLayout.PathElement.groupElement("chrV"));
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "sws_isSupportedInput",
        constants$1.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sws_isSupportedOutput",
        constants$1.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sws_isSupportedEndiannessConversion",
        constants$1.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "sws_alloc_context",
        constants$4.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "sws_init_context",
        constants$71.const$1
    );
}


