// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$340 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$340() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_filename_number_test",
        constants$0.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_sdp_create",
        constants$184.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_match_ext",
        constants$68.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "avformat_query_codec",
        constants$340.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "avformat_get_riff_video_tags",
        constants$4.const$0
    );
}


