// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$154 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$154() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_dict_parse_string",
        constants$154.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_dict_copy",
        constants$109.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_dict_free",
        constants$70.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_BYTE,
        JAVA_BYTE
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_dict_get_string",
        constants$154.const$4
    );
}


