// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$240 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$240() {}
    static final VarHandle const$0 = constants$239.const$4.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$1 = constants$239.const$4.varHandle(MemoryLayout.PathElement.groupElement("id"));
    static final VarHandle const$2 = constants$239.const$4.varHandle(MemoryLayout.PathElement.groupElement("pix_fmt"));
    static final VarHandle const$3 = constants$239.const$4.varHandle(MemoryLayout.PathElement.groupElement("capabilities"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(AVHWAccel.alloc_frame.class, "apply", constants$68.const$3);
    static final VarHandle const$5 = constants$239.const$4.varHandle(MemoryLayout.PathElement.groupElement("alloc_frame"));
}


