// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$99 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$99() {}
    static final UnionLayout const$0 = MemoryLayout.unionLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("__readers"),
            JAVA_INT.withName("__writers"),
            JAVA_INT.withName("__wrphase_futex"),
            JAVA_INT.withName("__writers_futex"),
            JAVA_INT.withName("__pad3"),
            JAVA_INT.withName("__pad4"),
            JAVA_INT.withName("__cur_writer"),
            JAVA_INT.withName("__shared"),
            JAVA_BYTE.withName("__rwelision"),
            MemoryLayout.sequenceLayout(7, JAVA_BYTE).withName("__pad1"),
            JAVA_LONG.withName("__pad2"),
            JAVA_INT.withName("__flags"),
            MemoryLayout.paddingLayout(4)
        ).withName("__data"),
        MemoryLayout.sequenceLayout(56, JAVA_BYTE).withName("__size"),
        JAVA_LONG.withName("__align")
    ).withName("");
    static final VarHandle const$1 = constants$99.const$0.varHandle(MemoryLayout.PathElement.groupElement("__align"));
    static final UnionLayout const$2 = MemoryLayout.unionLayout(
        MemoryLayout.sequenceLayout(8, JAVA_BYTE).withName("__size"),
        JAVA_LONG.withName("__align")
    ).withName("");
    static final VarHandle const$3 = constants$99.const$2.varHandle(MemoryLayout.PathElement.groupElement("__align"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "random",
        constants$86.const$5
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "srandom",
        constants$99.const$5
    );
}


