// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$175 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$175() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "av_frame_copy_props",
        constants$66.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_frame_get_plane_buffer",
        constants$122.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_frame_new_side_data",
        constants$118.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_frame_new_side_data_from_buf",
        constants$76.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_frame_get_side_data",
        constants$122.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_frame_remove_side_data",
        constants$160.const$2
    );
}


