// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "erf",
        constants$8.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "__erf",
        constants$8.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "erfc",
        constants$8.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "__erfc",
        constants$8.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "lgamma",
        constants$8.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "__lgamma",
        constants$8.const$4
    );
}


