// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$360 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$360() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_DOUBLE
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "sws_scaleVec",
        constants$360.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sws_normalizeVec",
        constants$360.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sws_freeVec",
        constants$72.const$4
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "sws_getDefaultFilter",
        constants$360.const$4
    );
}


