// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$358 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$358() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sws_scale_frame",
        constants$73.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "sws_frame_start",
        constants$73.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sws_frame_end",
        constants$72.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sws_send_slice",
        constants$340.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "sws_receive_slice",
        constants$340.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "sws_receive_slice_alignment",
        constants$0.const$3
    );
}


