// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$192 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$192() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "avcodec_find_decoder_by_name",
        constants$69.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "avcodec_find_encoder",
        constants$0.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "avcodec_find_encoder_by_name",
        constants$69.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "av_codec_is_encoder",
        constants$0.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "av_codec_is_decoder",
        constants$0.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_get_profile_name",
        constants$123.const$2
    );
}


