// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$100 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$100() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "initstate",
        constants$100.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "setstate",
        constants$69.const$2
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("fptr"),
        RuntimeHelper.POINTER.withName("rptr"),
        RuntimeHelper.POINTER.withName("state"),
        JAVA_INT.withName("rand_type"),
        JAVA_INT.withName("rand_deg"),
        JAVA_INT.withName("rand_sep"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("end_ptr")
    ).withName("random_data");
    static final VarHandle const$4 = constants$100.const$3.varHandle(MemoryLayout.PathElement.groupElement("fptr"));
    static final VarHandle const$5 = constants$100.const$3.varHandle(MemoryLayout.PathElement.groupElement("rptr"));
}


