// Generated by jextract

package com.chrisribble.ffmpeg5;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     long long quot;
 *     long long rem;
 * };
 * }
 */
public class lldiv_t {

    public static MemoryLayout $LAYOUT() {
        return constants$5.const$1;
    }
    public static VarHandle quot$VH() {
        return constants$86.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * long long quot;
     * }
     */
    public static long quot$get(MemorySegment seg) {
        return (long)constants$86.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * long long quot;
     * }
     */
    public static void quot$set(MemorySegment seg, long x) {
        constants$86.const$3.set(seg, x);
    }
    public static long quot$get(MemorySegment seg, long index) {
        return (long)constants$86.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void quot$set(MemorySegment seg, long index, long x) {
        constants$86.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle rem$VH() {
        return constants$86.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * long long rem;
     * }
     */
    public static long rem$get(MemorySegment seg) {
        return (long)constants$86.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * long long rem;
     * }
     */
    public static void rem$set(MemorySegment seg, long x) {
        constants$86.const$4.set(seg, x);
    }
    public static long rem$get(MemorySegment seg, long index) {
        return (long)constants$86.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void rem$set(MemorySegment seg, long index, long x) {
        constants$86.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


